kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: eks-ministack
nodes:
  - role: control-plane
    image: kindest/node:v1.32.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30080
        hostPort: 9090
        protocol: TCP
  - role: worker
    image: kindest/node:v1.32.0
    labels:
      topology.kubernetes.io/zone: us-east-1a
  - role: worker
    image: kindest/node:v1.32.0
    labels:
      topology.kubernetes.io/zone: us-east-1a
  - role: worker
    image: kindest/node:v1.32.0
    labels:
      topology.kubernetes.io/zone: us-east-1b
  - role: worker
    image: kindest/node:v1.32.0
    labels:
      topology.kubernetes.io/zone: us-east-1b
