prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    retention: 2h
    storageSpec: {}

grafana:
  adminPassword: admin123
  persistence:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.eks-ministack.local

alertmanager:
  enabled: false
